spring.application.name=drivemind-backend

spring.datasource.url=jdbc:mysql://localhost:3306/drivemind
spring.datasource.username=root
spring.datasource.password=Meet.123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
